version: '3'

dotenv:
  - ".env"

tasks:
  update-vscode-win:
    internal: true
    platforms: [windows]
    dir: "./vscode/{{.MACHINE_NAME}}"
    cmds:
      - cp "${HOME}/AppData/Roaming/Code/User/keybindings.json" .
      - cp "${HOME}/AppData/Roaming/Code/User/settings.json" .
