# Building LLVM with CMake — LLVM 21.1.2 documentation
# https://releases.llvm.org/21.1.2/docs/CMake.html

version: "3"
tasks:
  configure-release:
    desc: "configure release build"
    vars:
      args: >-
        -G Ninja
        -S llvm-project/llvm
        -B llvm-project/build/release
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX={{.HOME}}/local/llvm/llvm@21
        -DDEFAULT_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
        -DLLVM_CCACHE_BUILD=ON
        -DLLVM_ENABLE_PROJECTS="clang;lld"
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
        -DLLVM_TARGETS_TO_BUILD="AArch64;RISCV;MSP430;X86"
    cmd: cmake {{ .args }}
  configure-debug:
    desc: "configure debug build"
    vars:
      args: >-
        -G Ninja
        -S llvm-project/llvm
        -B llvm-project/build/debug
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_INSTALL_PREFIX={{.HOME}}/local/llvm/llvm@21
        -DDEFAULT_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
        -DLLVM_CCACHE_BUILD=ON
        -DLLVM_ENABLE_PROJECTS="clang;lld"
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
        -DLLVM_TARGETS_TO_BUILD="AArch64;RISCV;MSP430"
    cmd: cmake {{ .args }}

  build-release:
    desc: "build release"
    dir: llvm-project/build/release
    preconditions:
      - sh: test -f build.ninja
        msg: '"build.ninja" does not exist.'
    cmd: ninja

  build-debug:
    desc: "build debug"
    dir: llvm-project/build/debug
    preconditions:
      - sh: test -f build.ninja
        msg: '"build.ninja" does not exist.'
    cmd: ninja

  rm-release:
    desc: "remove release build artifacts"
    cmd: rm -rf llvm-project/build/release

  rm-debug:
    desc: "remove debug build artifacts"
    cmd: rm -rf llvm-project/build/debug

  install:
    desc: "install release"
    dir: llvm-project/build/release
    cmd: ninja install

  uninstall:
    desc: "uninstall release"
    cmd: rm -rf {{.HOME}}/local/llvm/llvm@21
