# Building LLVM with CMake — LLVM 21.1.0 documentation
# https://releases.llvm.org/21.1.0/docs/CMake.html

version: "3"
vars:
  INSTALL_PREFIX: "{{.HOME}}/local/llvm-21.1.8"

tasks:
  release:configure:
    desc: "configure release build"
    vars:
      args: >-
        -G Ninja
        -S llvm
        -B build/release
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX={{.INSTALL_PREFIX}}
        -DDEFAULT_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
        -DLLVM_CCACHE_BUILD=ON
        -DLLVM_ENABLE_PROJECTS="clang;lld"
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
        -DLLVM_TARGETS_TO_BUILD="AArch64;RISCV;MSP430;X86"
    cmd: cmake {{ .args }}
  debug:configure:
    desc: "configure debug build"
    vars:
      args: >-
        -G Ninja
        -S llvm
        -B build/debug
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_INSTALL_PREFIX={{.INSTALL_PREFIX}}
        -DDEFAULT_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
        -DLLVM_CCACHE_BUILD=ON
        -DLLVM_ENABLE_PROJECTS="clang;lld"
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
        -DLLVM_TARGETS_TO_BUILD="AArch64;RISCV;MSP430;X86"
    cmd: cmake {{ .args }}

  release:build:
    desc: "build release"
    dir: build/release
    preconditions:
      - sh: test -f build.ninja
        msg: '"build.ninja" does not exist.'
    cmd: ninja

  debug:build:
    desc: "build debug"
    dir: build/debug
    preconditions:
      - sh: test -f build.ninja
        msg: '"build.ninja" does not exist.'
    cmd: ninja

  release:clean:
    desc: "remove release build artifacts"
    cmd: rm -rf build/release

  debug:clean:
    desc: "remove debug build artifacts"
    cmd: rm -rf build/debug

  release:install:
    desc: "install release"
    dir: build/release
    cmd: ninja install

  release:uninstall:
    desc: "uninstall release"
    cmd: rm -rf {{.INSTALL_PREFIX}}
